// import { images } from '../constants'

export const RadioisotopeData = [
    {
        id: '1',
        // image: images.diagnostic,
        name: 'Diagnostic Radioisotope',
        date: 'General',
        elements: [
            {
                id: 'e1',
                name: 'Carbon-11',
                symbol: 'C-11',
                period: 2,
                group: 14,
                atomicNumber: 6,
                atomicWeight: 11.011,
                halfLife: '20.364 minutes',
                productionMethod: 'Cyclotron, Nuclear fission ',
                energy: 'β+ = 1.982MeV',
                energyType: 'Positron emission',
                oxidationstate: 4,
                parentRadionuclide: ' 14N(p,α)11C',
                decayproduct: 'B-11',
                naturalstructure: 'Tetrahedral',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/carbon11.png'),

                // ... other details
            },
            {
                id: 'e2',
                name: 'Copper62',
                symbol: 'Cu-62',
                period: 4,
                group: 11,
                atomicNumber: 29,
                atomicWeight: 61.932,
                halfLife: '9.67 minutes',
                productionMethod: 'Cyclotron',
                energy: 'β+ = 1.316MeV',
                energyType: 'Positron emission',
                oxidationstate: 2,
                parentRadionuclide: 'Zn-62',
                decayproduct: 'Ni-62',
                naturalstructure: 'Face centred cubic crystal (FCC)',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/copper62.png'),

                // ... other details
            },
            {
                id: 'e3',
                name: 'Copper-64',
                symbol: 'Cu-64',
                period: 4,
                group: 11,
                atomicNumber: 29,
                atomicWeight: 63.929,
                halfLife: '12.70hrs',
                productionMethod: 'Cyclotron',
                energy: 'β+ = 0.2782MeV,β- = 0.1902MeV,γ = 1346KeV',
                energyType: 'Positron emission',
                oxidationstate: 2,
                parentRadionuclide: '64Ni(p,n)64Cu',
                decayproduct: 'Zn-64, Ni-64',
                naturalstructure: 'Face centred cubic crystal (FCC)',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/copper64.png'),

                // ... other details
            },
            {
                id: 'e4',
                name: 'Fluorine-18',
                symbol: 'F-18',
                period: 2,
                group: 17,
                atomicNumber: 9,
                atomicWeight: 18,
                halfLife: '109.77mins',
                productionMethod: 'Cyclotron',
                energy: 'β+ = 0.635MeV',
                energyType: 'Positron emission',
                oxidationstate: -1,
                parentRadionuclide: 'Ne-18',
                decayproduct: 'O-18',
                naturalstructure: 'Cubic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/fluorine18.png'),
            },
            {
                id: 'e5',
                name: 'Gallium-67',
                symbol: 'Ga-67',
                period: 4,
                group: 13,
                atomicNumber: 31,
                atomicWeight: 66.928,
                halfLife: '3.2617days',
                productionMethod: 'Generator',
                energy: 'γ = 1077.34 KeV , β+ = 836KeV', //value not given
                energyType: 'Gamma,Beta',
                oxidationstate: 3,
                parentRadionuclide: 'Ge-67, 68Zn (p,2n)67Ga',
                decayproduct: 'Zn-67',
                naturalstructure: 'Orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Gallium67.png'),
            },
            {
                id: 'e6',
                name: 'Gallium-68',
                symbol: 'Ga-68',
                period: 4,
                group: 13,
                atomicNumber: 31,
                atomicWeight: 67.927,
                halfLife: '67.71mins',
                productionMethod: 'Generator',
                energy: 'β+ = 0.836MeV,β- = 1077KeV',
                energyType: 'Gamma',
                oxidationstate: 3,
                parentRadionuclide: 'Ge-68',
                decayproduct: 'Zn-68',
                naturalstructure: 'Orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Gallium68.png'),
            },
            {
                id: 'e7',
                name: 'Indium-111',
                symbol: 'In-111',
                period: 5,
                group: 13,
                atomicNumber: 49,
                atomicWeight: 110.905,
                halfLife: '2.8047days',
                productionMethod: 'Cyclotron',
                energy: 'γ = 173,247',
                energyType: 'Gamma',
                oxidationstate: '1+3',
                parentRadionuclide: '112Cd(p,2n)111In, Sn-111,In-111m1',
                decayproduct: 'Cd-111',
                naturalstructure: 'Tetragonal crystal',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Indium111.png'),
            },
            {
                id: 'e8',
                name: 'Indium-113m',
                symbol: 'In113m',
                period: 5,
                group: 13,
                atomicNumber: 49,
                atomicWeight: 112.9,
                halfLife: '99.476mins',
                productionMethod: 'Cyclotron',
                energy: 'γ = 391.698 Kev', //value not given
                energyType: 'Gamma',
                oxidationstate: '1+3',
                parentRadionuclide: 'Sn-113',
                decayproduct: 'stable',
                naturalstructure: 'Tetragonal crystal',
                // decayimage: '',
            },
            {
                id: 'e9',
                name: 'Iodine-123',
                symbol: 'I-123',
                period: 5,
                group: 17,
                atomicNumber: 53,
                atomicWeight: 122.90559,
                halfLife: '13.2230hrs',
                productionMethod: 'Cyclotron',
                energy: 'γ = 159KeV',
                energyType: 'beta-,gamma',
                oxidationstate: -1,
                parentRadionuclide: 'Xe-123',
                decayproduct: 'Te-123',
                naturalstructure: 'base-centered orthorhombic',
                // decayimage: '',
            },
            {
                id: 'e10',
                name: 'Iodine-124',
                symbol: 'I-124',
                period: 5,
                group: 17,
                atomicNumber: 53,
                atomicWeight: 123.90621,
                halfLife: '4.1760days',
                productionMethod: 'Cyclotron',
                energy: 'β+ = 2.13MeV,β- = 1532, 2135KeV,γ = 511, 603KeV',
                energyType: 'Beta, Gamma',
                oxidationstate: -1,
                parentRadionuclide: '124Te(p, n)124I',
                decayproduct: 'Te-124',
                naturalstructure: 'base-centered orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Iodine124.jpg'),
            },
            {
                id: 'e11',
                name: 'Iodine-125',
                symbol: 'I-125',
                period: 5,
                group: 17,
                atomicNumber: 53,
                atomicWeight: 124.9046,
                halfLife: '59.407days',
                productionMethod: 'Nuclear reactor',
                energy: 'γ = 35',
                energyType: 'Gamma',
                oxidationstate: -1,
                parentRadionuclide: 'Xe-125',
                decayproduct: 'Te-125',
                naturalstructure: 'base-centered orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/iodine125.png'),
            },
            {
                id: 'e12',
                name: 'Iodine-131',
                symbol: 'I-131',
                period: 5,
                group: 17,
                atomicNumber: 53,
                atomicWeight: 130.9061,
                halfLife: '8.025days',
                productionMethod: 'Nuclear fission',
                energy: 'β- = 191.6KeV ,γ = 364.489 KeV',
                energyType: 'Beta',
                oxidationstate: -1,
                parentRadionuclide: 'Te-131,Te-131m',
                decayproduct: 'Xe-131',
                naturalstructure: 'base-centered orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Iodine131.jpg'),
            },
            {
                id: 'e13',
                name: 'Krypton-81m',
                symbol: 'Kr-81m',
                period: 4,
                group: 18,
                atomicNumber: 36,
                atomicWeight: '80.91659',
                halfLife: '13.10secs',
                productionMethod: 'Generator',
                energy: 'γ = 190',
                energyType: 'Gamma',
                oxidationstate: '0/+2',
                parentRadionuclide: 'Ru-81',
                decayproduct: 'Kr-81,Br-81',
                naturalstructure: 'Face centred cubic crystal (FCC)',
                // decayimage: '',
            },
            {
                id: 'e14',
                name: 'Nitrogen-13',
                symbol: 'N-13',
                period: 2,
                group: 15,
                atomicNumber: 7,
                atomicWeight: 13,
                halfLife: '9.965mi',
                productionMethod: 'Cyclotron',
                energy: 'β+ = 2.2205MeV',
                energyType: 'Positron emission',
                oxidationstate: '±Ʒ,+5',
                parentRadionuclide: '16O(p,α)13N',
                decayproduct: 'C-13',
                naturalstructure: 'Hexagonal ',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/nitrogen13.png'),
            },
            {
                id: 'e15',
                name: 'Oxygen-15',
                symbol: 'O-15',
                period: 2,
                group: 16,
                atomicNumber: 8,
                atomicWeight: 15,
                halfLife: '122.24secs',
                productionMethod: 'Cyclotron',
                energy: 'β+ = 2.754MeV',
                energyType: 'Positron emission',
                oxidationstate: -2,
                parentRadionuclide: 'F-16',
                decayproduct: 'N-15',
                naturalstructure: 'Orthorhombic ',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/oxygen15.png'),
            },
            {
                id: 'e16',
                name: 'Rubidium-82',
                symbol: 'Ru-82',
                period: 5,
                group: 1,
                atomicNumber: 44,
                atomicWeight: '81.91821 g/mol',
                halfLife: '75seconds',
                productionMethod: 'Generator',
                energy: 'β+ = 1.535MeV,β- = 777KeV',
                energyType: 'Positron emission',
                oxidationstate: 1,
                parentRadionuclide: 'Sr-82',
                decayproduct: 'Kr-82',
                naturalstructure: 'body-centered cubic crystal',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Rubidium82.png'),
            },
            {
                id: 'e17',
                name: 'Technitium-94m',
                symbol: 'Tc-94m',
                period: 5,
                group: 7,
                atomicNumber: 43,
                atomicWeight: 93.909,
                halfLife: '52.5min',
                productionMethod: 'Nuclear reactor',
                energy: 'β+ = 2.47MeV',
                energyType: 'Positron emission',
                oxidationstate: 7,
                parentRadionuclide: '94Mo(p,n)94mTc',
                decayproduct: 'Mo-94',
                naturalstructure: 'Hexagonal close packed(HCP)',
                // decayimage: '',
            },
            {
                id: 'e18',
                name: 'Technitium-99m',
                symbol: 'Tc-99m',
                period: 5,
                group: 7,
                atomicNumber: 43,
                atomicWeight: 98.9,
                halfLife: '6.00hrs',
                productionMethod: 'Generator',
                energy: 'γ = 140.5KeV',
                energyType: 'Gamma',
                oxidationstate: 7,
                parentRadionuclide: 'Mo-99',
                decayproduct: 'Ru-99',
                naturalstructure: 'Hexagonal close packed(HCP)',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Technitium99.png'),
            },
            {
                id: 'e19',
                name: 'Thallium-201',
                symbol: 'Tl-201',
                period: 6,
                group: 13,
                atomicNumber: 81,
                atomicWeight: 200.97,
                halfLife: '3.0421hrs',
                productionMethod: 'Cyclotron',
                energy: 'gamma = 135,167',
                energyType: 'Gamma',
                oxidationstate: 1,
                parentRadionuclide: 'Pb-201, Tl-201m',
                decayproduct: 'Hg-201',
                naturalstructure: 'Hexagonal close packed(HCP)',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Thallium201.jpg'),
            },
            {
                id: 'e20',
                name: 'Xenon-133',
                symbol: 'Xe-133',
                period: 5,
                group: 18,
                atomicNumber: 54,
                atomicWeight: 132.905,
                halfLife: '5.2475days',
                productionMethod: 'Reactor Produced',
                energy: 'β- = 427',
                energyType: 'Beta, Gamma',
                oxidationstate: '6,4,2',
                parentRadionuclide: 'I-133',
                decayproduct: 'Cs-133',
                naturalstructure: 'Face centred cubic crystal (FCC)',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Xenon133.jpg'),
            },
        ],
    },
    {
        id: '2',
        // image: images.therapeutic,
        name: 'Therapeutic Radioisotope',
        date: 'General',
        elements: [
            {
                id: 'e1',
                name: 'Phosphor-32',
                symbol: 'P-32',
                period: 3,
                group: 15,
                atomicNumber: 15,
                atomicWeight: 31.97,
                halfLife: '14.3',
                productionMethod: 'Reactor produced',
                energy: 'β- = 695 KeV',
                energyType: 'βˉ',
                oxidationstate: -3,
                parentRadionuclide: 'Si-32',
                decayproduct: 'S-32',
                naturalstructure: 'Cubic crystal structure ',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/phosphorus32.png'),

                // ... other details
            },
            {
                id: 'e2',
                name: 'Scandium-47',
                symbol: 'Sc-47',
                period: 4,
                group: 3,
                atomicNumber: 21,
                atomicWeight: 46.95,
                halfLife: '3.3',
                productionMethod: 'Reactor produced (47Ti9(n,p)47Sc)',
                energy: 'β- = 162,γ = 159',
                energyType: 'βˉ',
                oxidationstate: 3,
                parentRadionuclide: 'Ca-47',
                decayproduct: 'Ti-47',
                naturalstructure:
                    'α- Close packed hexagonal,β- Body centered cubic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Scandium47.jpg'),


                // ... other details
            },
            {
                id: 'e3',
                name: 'Copper-67',
                symbol: 'Cu-67',
                period: 4,
                group: 11,
                atomicNumber: 29,
                atomicWeight: '66.92AMU',
                halfLife: '2.6',
                productionMethod: 'Reactor produced(67Zn(n,p)67Cu)',
                energy: 'β- = 121 KeV,γ = 185',
                energyType: 'βˉ',
                oxidationstate: '+1,+2',
                parentRadionuclide: 'Ni-67',
                decayproduct: 'Zn-67',
                naturalstructure: 'FCC',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Copper67.jpg'),

                // ... other details
            },

            {id: 'e4',
            name: 'Gallium-67',
            symbol: 'Ga-67',
            period: 4,
            group: 13,
            atomicNumber: 31,
            atomicWeight: 66.92,
            halfLife: '3.3 days',
            productionMethod: 'Cyclotron',
            energy: 'Auger electron energy = 0.742 KeV,γ = 93.310 KeV',
            energyType: 'Aug,γ',
            oxidationstate: 3,
            parentRadionuclide: 'Ge-67',
            decayproduct: 'Zn-67',
            naturalstructure: 'Orthorhombic',
            // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Gallium67.png'),
                // ... other details
            },

            {
                id: 'e5',
                name: 'Astatine-211',
                symbol: 'At-211',
                period: 6,
                group: 17,
                atomicNumber: 85,
                atomicWeight: 210.98,
                halfLife: '7.214hrs',
                productionMethod: 'reactor produced',
                energy: 'α = 5869.5 KeV,γ = 669.78 KeV, 687 KeV',
                energyType: 'α,γ',
                oxidationstate: '-1,+2,+3',
                parentRadionuclide: '215Fr, At-211m, Rn-211',
                decayproduct: 'Po-211, Bi-207',
                naturalstructure: 'Orthorhombic Crystalline',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Astatine77.jpg'),
                // ... other details
            },

            {
                id: 'e6',
                name: 'Strontium-89',
                symbol: 'Sr-89',
                period: 5,
                group: 2,
                atomicNumber: 38,
                atomicWeight: 88.9,
                halfLife: '50.5',
                productionMethod: 'Reactor Produced (89Y(n,p)89Sr)',
                energy: 'β- = 583',
                energyType: 'βˉ',
                oxidationstate: 2,
                parentRadionuclide: 'Rb-89',
                decayproduct: 'Y-89',
                naturalstructure: 'FCC',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Strontium89.jpg'),

                // ... other details
            },

            {
                id: 'e7',
                name: 'Yttrium-90',
                symbol: 'Y-90',
                period: 5,
                group: 3,
                atomicNumber: 39,
                atomicWeight: 88.9,
                halfLife: '2.7',
                productionMethod: 'Nuclear decay of Sr90',
                energy: 'β- = 935',
                energyType: 'βˉ',
                oxidationstate: 3,
                parentRadionuclide: 'Sr-90,Y-90m',
                decayproduct: 'Zr-90',
                naturalstructure:
                    'α- Close packed hexagonal,β- Body centered cubic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Yttrium90.png'),


                // ... other details
            },

            {
                id: 'e8',
                name: 'Rhodium-105',
                symbol: 'Rh-105',
                period: 5,
                group: 9,
                atomicNumber: 45,
                atomicWeight: 104.9,
                halfLife: '1.5',
                productionMethod: 'Cyclotron,Reactor produced(104Ru(n,y)Rh105)',
                energy: 'β- = 179.3 Kev,γ = 319',
                energyType: 'βˉ,γ',
                oxidationstate: 3,
                parentRadionuclide: 'Ru-105,Rh-105m',
                decayproduct: 'Pd-105',
                naturalstructure: 'FCC',
                // decayimage: '',

                // ... other details
            },

            {
                id: 'e9',
                name: 'Palladium-109',
                symbol: 'Pd-109',
                period: 5,
                group: 10,
                atomicNumber: 46,
                atomicWeight: 108.9,
                halfLife: '0.6',
                productionMethod: 'Reactor produced',
                energy: 'β- = 360,γ = 88',
                energyType: 'βˉ,γ',
                oxidationstate: '0,2',
                parentRadionuclide: 'Rh-109,Pd-109m1',
                decayproduct: 'Ag-109',
                naturalstructure: 'FCC',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Palladium109.jpg'),

                // ... other details
            },

            {
                id: 'e10',
                name: 'Silver-111',
                symbol: 'Ag-111',
                period: 5,
                group: 11,
                atomicNumber: 47,
                atomicWeight: 110.9,
                halfLife: '7.5',
                productionMethod: 'Reaactor produced (nat-Pd(d,x)111Ag)',
                energy: 'β-: = 350,γ = 342',
                energyType: 'βˉ,γ',
                oxidationstate: 1,
                parentRadionuclide: 'Pd-111,Ag-111m1,Pd-111m1',
                decayproduct: 'Cd-111',
                naturalstructure: 'FCC',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Silver111.jpg'),


                // ... other details
            },

            {
                id: 'e11',
                name: 'Indium-111',
                symbol: 'In-111',
                period: 5,
                group: 13,
                atomicNumber: 49,
                atomicWeight: 110.9,
                halfLife: '2.8',
                productionMethod: 'Cyclotron (112Cd(p,2n)111In)',
                energy: 'Auger electron energy = 1.992 KeV,γ = 171.80, 245.35',
                energyType: 'Aug,γ',
                oxidationstate: '1,3',
                parentRadionuclide: 'Sn-111,In-111m1',
                decayproduct: 'Cd-111',
                naturalstructure: 'Centered tetragonal',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Indium111.png'),


                // ... other details
            },
            {
                id: 'e12',
                name: 'Tin-117m',
                symbol: 'Sn-117m',
                period: 5,
                group: 14,
                atomicNumber: 50,
                atomicWeight: '116.902AMU',
                halfLife: 14,
                productionMethod: 'Reactor produced(116Sn(n,y)117mSn',
                energy: 'β- = 127-152,γ = 158.56 Kev, 156.02 Kev',
                energyType: 'γ,CE',
                oxidationstate: '4,2',
                parentRadionuclide: 'Sn-116',
                decayproduct: 'Sn-117',
                naturalstructure: 'Body centered tetragonal',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Tin117m.jpg'),
                // ... other details
            },
            {
                id: 'e13',
                name: 'Iodine-123',
                symbol: 'I-123',
                period: 5,
                group: 17,
                atomicNumber: 53,
                atomicWeight: 122.9,
                halfLife: '13.2',
                productionMethod: 'Cyclotron (Xe125(p,2n)123I)',
                energy: 'Auger electron energy = 2.323 KeV,γ = 159 Kev',
                energyType: 'Aug,γ',
                oxidationstate: '-1,+1,+3,+5,+7',
                parentRadionuclide: 'Xe-123',
                decayproduct: 'Te-123',
                naturalstructure: 'Base centered orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Iodine123.jpg'),
                // ... other details
            },

            {
                id: 'e14',
                name: 'iodine-125',
                symbol: 'I-125',
                period: 5,
                group: 17,
                atomicNumber: 53,
                atomicWeight: 124.9,
                halfLife: '59.407days',
                productionMethod: 'Reactor produced',
                energy: 'Auger electron energy = 2.323 KeV,γ = 35.49 Kev',
                energyType: 'Aug,γ',
                oxidationstate: '-1,+1,+3,+5,+7',
                parentRadionuclide: 'Xe-125',
                decayproduct: 'Te-125',
                naturalstructure: 'Base centered orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/iodine125.png'),
                // ... other details
            },

            {
                id: 'e15',
                name: 'Iodine-131',
                symbol: 'I-131',
                period: 5,
                group: 17,
                atomicNumber: 53,
                atomicWeight: 130.9,
                halfLife: '8',
                productionMethod: 'Reactor produced',
                energy: 'β- = 181,γ = 364',
                energyType: 'βˉ',
                oxidationstate: '-1,+1,+3,+5,+7',
                parentRadionuclide: 'Te-131,Te-131m',
                decayproduct: 'Xe-131',
                naturalstructure: 'Base centered orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Iodine131.jpg'),
                // ... other details
            },

            {
                id: 'e16',
                name: 'Samarium-153',
                symbol: 'Sm-153',
                period: 6,
                group: 'lanthanide',
                atomicNumber: 62,
                atomicWeight: 152.92,
                halfLife: '46.284days',
                productionMethod: 'Reactor produced (152Sm(n,y)153Sm)',
                energy: 'β- = 225.2 Kev,γ = 103.180 Kev',
                energyType: 'βˉ,γ',
                oxidationstate: 3,
                parentRadionuclide: 'Pm-153,Sm-153m',
                decayproduct: 'Eu-153',
                naturalstructure: 'Rhombohedral',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Samarium153.jpg'),

                // ... other details
            },
            {
                id: 'e17',
                name: 'Gadolinium-159',
                symbol: 'Gd-159',
                period: 6,
                group: 'lanthanide',
                atomicNumber: 64,
                atomicWeight: 158.92,
                halfLife: '0.8',
                productionMethod: 'Reactor Produced(158Gd(n,y)159Gd)',
                energy: 'β- = 326.9 Kev,γ = 363',
                energyType: 'βˉ,γ',
                oxidationstate: 3,
                parentRadionuclide: 'Eu-159',
                decayproduct: 'Tb-159',
                naturalstructure:
                    'α- Hexagonal close, β-Body centered tetragonal',
                // decayimage: '',

                // ... other details
            },

            {
                id: 'e18',
                name: 'Lutetium-177',
                symbol: 'Lu-177',
                period: 6,
                group: 'lanthanide',
                atomicNumber: 71,
                atomicWeight: 176.94,
                halfLife: '6.7',
                productionMethod: 'Reactor produced',
                energy: 'β- = 148.8 Kev,γ = 208',
                energyType: 'βˉ,γ',
                oxidationstate: 3,
                parentRadionuclide: 'Yb-177,Lu-177m4',
                decayproduct: 'Hf-177',
                naturalstructure: 'Close packed hexagonal',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Lutetium177.jpg'),

                // ... other details
            },
            {
                id: 'e19',
                name: 'Rhenium-186',
                symbol: 'Re-186',
                period: 6,
                group: 7,
                atomicNumber: 75,
                atomicWeight: 185.95,
                halfLife: '3.7',
                productionMethod: 'Reactor produced (185Re(n,y)186Re)',
                energy: 'β- = 360.5 Kev,γ = 137',
                energyType: 'βˉ,γ',
                oxidationstate: '4,7',
                parentRadionuclide: 'Re-186m1',
                decayproduct: 'Os-186, W-186',
                naturalstructure: 'Hexagonal closed packed',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Rhemium186.jpg'),

                // ... other details
            },

            {
                id: 'e20',
                name: 'Rhenium-188',
                symbol: 'Re-188',
                period: 6,
                group: 7,
                atomicNumber: 75,
                atomicWeight: 187.95,
                halfLife: '0.7',
                productionMethod: 'Generator produced',
                energy: 'β- = 795,γ = 155',
                energyType: 'βˉ,γ',
                oxidationstate: '4,7',
                parentRadionuclide: 'W-188,Re-188m',
                decayproduct: 'Os-188',
                naturalstructure: 'Hexagonal closed packed',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Rhemium188.jpg'),

                // ... other details
            },
        ],
    },
    {
        id: '3',
        // image: images.theranostic,
        name: 'Theragnostic Radioisotope',
        date: 'General',
        elements: [
            {
                id: 'e1',
                name: 'Scandium-47',
                symbol: 'Sc-47',
                period: 4,
                group: 3,
                atomicNumber: 21,
                atomicWeight: '46.95AMU',
                halfLife: '3.3days',
                productionMethod: 'Reactor produced (47Ti9(n,p)47Sc)',
                energy: 'βˉ = 162,γ = 159',
                energyType: 'βˉ',
                oxidationstate: 3,
                parentRadionuclide: 'Ca-47',
                decayproduct: 'Ti-47',
                naturalstructure:
                    'α- Close packed hexagonal,β- Body centered cubic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Scandium47.jpg'),
            },
            {
                id: 'e2',
                name: 'Copper-67',
                symbol: 'Cu-67',
                period: 4,
                group: 11,
                atomicNumber: 29,
                atomicWeight: '66.92AMU',
                halfLife: '2.6days',
                productionMethod: 'Reactor produced(67Zn(n,p)67Cu)',
                energy: 'βˉ = 141',
                energyType: 'βˉ',
                oxidationstate: '+1,+2',
                parentRadionuclide: 'Ni-67',
                decayproduct: 'Zn-67',
                naturalstructure: 'FCC',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Copper67.jpg'),
            },
            {
                id: 'e3',
                name: 'Gallium-67',
                symbol: 'Ga-67',
                period: 4,
                group: 13,
                atomicNumber: 31,
                atomicWeight: '66.92AMU',
                halfLife: '3.3days',
                productionMethod: 'Cyclotron',
                energy: 'Auger electron energy = 0.742 KeV,γ = 93.310 KeV ',
                energyType: 'Aug,γ',
                oxidationstate: 3,
                parentRadionuclide: 'Ge-67',
                decayproduct: 'Zn-67',
                naturalstructure: 'Orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Gallium67.png'),
            },
            {
                id: 'e4',
                name: 'Indium-111',
                symbol: 'In-111',
                period: 5,
                group: 13,
                atomicNumber: 49,
                atomicWeight: '110.9AMU',
                halfLife: '2.8days',
                productionMethod: 'Cyclotron (112Cd(p,2n)111In)',
                energy: 'βˉ = 1.992 keV,γ = 171.80, 245.35',
                energyType: 'Aug,γ',
                oxidationstate: '1,3',
                parentRadionuclide: 'Sn-111,In-111m1',
                decayproduct: 'Cd-111',
                naturalstructure: 'Centered tetragonal',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Indium111.png'),
            },
            {
                id: 'e5',
                name: 'Tin-117m',
                symbol: 'Sn-117m',
                period: 5,
                group: 14,
                atomicNumber: 50,
                atomicWeight: '116.902AMU',
                halfLife: '14days',
                productionMethod: 'Reactor produced(116Sn(n,y)117mSn',
                energy: 'γ = 158.56 kev, 156.02 kev',
                energyType: 'CE,γ',
                oxidationstate: '4,2',
                parentRadionuclide: 'Sn-116',
                decayproduct: 'Sn-117',
                naturalstructure: 'Body centered tetragonal',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Tin117m.jpg'),
            },
            {
                id: 'e6',
                name: 'Iodine-123',
                symbol: 'I-123',
                period: 5,
                group: 17,
                atomicNumber: '53AMU',
                atomicWeight: '122.9',
                halfLife: '13.2days',
                productionMethod: 'Cyclotron (Xe125(p,2n)123I)',
                energy: 'Aug electron energy = 2.323 kev,γ = 159 kev', 
                energyType: 'Aug,γ',
                oxidationstate: '-1,+1,+3,+5,+7',
                parentRadionuclide: 'Xe-123',
                decayproduct: 'Te-123',
                naturalstructure: 'Base centered orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Iodine123.jpg'),
            },
            {
                id: 'e7',
                name: 'Iodine-131',
                symbol: 'I-131',
                period: 5,
                group: 17,
                atomicNumber: 53,
                atomicWeight: '130.9AMU',
                halfLife: '8days',
                productionMethod: 'Reactor produced',
                energy: 'βˉ = 191,γ = 364',
                energyType: 'βˉ',
                oxidationstate: '-1,+1,+3,+5,+7',
                parentRadionuclide: 'Te-131,Te-131m',
                decayproduct: 'Xe-131',
                naturalstructure: 'Base centered orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Iodine131.jpg'),
            },
            {
                id: 'e8',
                name: 'Samarium-153',
                symbol: 'Sm-153',
                period: 6,
                group: 'lanthanide',
                atomicNumber: '62AMU',
                atomicWeight: 152.92,
                halfLife: '1.9days',
                productionMethod: 'Reactor produced (152Sm(n,y)153Sm)',
                energy: 'βˉ = 225,γ = 103',
                energyType: 'βˉ',
                oxidationstate: 3,
                parentRadionuclide: 'Pm-153,Sm-153m',
                decayproduct: 'Eu-153',
                naturalstructure: 'Rhombohedral',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Samarium153.jpg'),
            },
            {
                id: 'e9',
                name: 'Astatine-211',
                symbol: 'At-211',
                period: 6,
                group: 17,
                atomicNumber: 85,
                atomicWeight: '210.98AMU',
                halfLife: '7.214hours',
                productionMethod: 'reactor produced',
                energy: 'α = 5869.5 KeV ,γ = 669.78 KeV , 687KeV',
                energyType: 'α,γ',
                oxidationstate: '-1, +2, +3',
                parentRadionuclide: '215Fr, At-211m,Rn-211',
                decayproduct: 'Po-211, Bi-207',
                naturalstructure: 'Orthorhombic Crystalline',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Astatine77.jpg'),
            },
            {
                id: 'e10',
                name: 'Bismuth-213',
                symbol: 'Bi-213',
                period: 6,
                group: 15,
                atomicNumber: 83,
                atomicWeight: '213AMU',
                halfLife: '45.59mins',
                productionMethod:
                    'Single-column "direct" 225Ac/213Bi generator with AG MP-50 resin',
                energy: 'α = 5.982Mev,βˉ = 1.426Mev,γ = 441',
                energyType: 'βˉ,α,γ',
                oxidationstate: '3,5',
                parentRadionuclide: 'Pb213, At217',
                decayproduct: 'Po213,Tl209',
                naturalstructure: 'Rhombohedral lattice',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Bismuth213.jpg'),
            },
            {
                id: 'e11',
                name: 'Scandium-44/Scandium-47',
                symbol: 'Sc-44/Sc-47',
                period: 4,
                group: 3,
                atomicNumber: 21,
                atomicWeight: '43.95AMU/46.95AMU',
                halfLife: '4.0420hrs/3.3492days',
                productionMethod:
                    'Nuclear reactor producedCa(p,n)44Sc/Reactor produced (47Ti9(n,p)47Sc)',
                energy: 'β+ = 632KeV,βˉ = 162,γ = 1157KeV',
                energyType: 'β+,γ/βˉ',
                oxidationstate: 3,
                parentRadionuclide: 'Ti44, Sc44m',
                decayproduct: 'Ca44',
                naturalstructure:
                    'α- Close packed hexagonal,β- Body centered cubic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/TheragnosticScandium44.jpg'),
                // decayimage2: require('../assets/radioisotopeimages/diagnoticimages/TheragnosticScandium47.png'),
            },
            {
                id: 'e12',
                name: 'Copper-64/Copper67',
                symbol: 'Cu-64/ Cu-67',
                period: 4,
                group: 11,
                atomicNumber: 29,
                atomicWeight: '63.929AMU/66.927AMU',
                halfLife: '12.70hrs/61.83hrs',
                productionMethod:
                    'Nuclear reactor 64Ni(p,n)64Cu and accelarator produced / Reactor produced(67Zn(n,p)67Cu)',
                energy: 'β+ = 278.01,βˉ = 190.74/141',
                energyType: 'β+,β-/β-',
                oxidationstate: '+1,+2',
                parentRadionuclide: 'Ni67',
                decayproduct: 'Ni64, Zn64/ Zn67',
                naturalstructure: 'FCC(face centered cubic)',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/Theragnosticcopper64.png'),
                // decayimage2: require('../assets/radioisotopeimages/diagnoticimages/Theragnosticcopper67.png'),
            },
            {
                id: 'e13',
                name: 'Gallium-68/Gallium-67',
                symbol: 'Ga-68/Ga-67',
                period: 4,
                group: 13,
                atomicNumber: 31,
                atomicWeight: '67.927AMU/66.928AMU',
                halfLife: '67.71mins/3.2617days',
                productionMethod: 'generator produced/ Cyclotron',
                energy: 'β+ = 836,γ = 93, 184, 300',
                energyType: 'β+/γ',

                oxidationstate: 3,
                parentRadionuclide: 'Ge67/ Ge68',
                decayproduct: 'Zn67/Zn68',
                naturalstructure: 'Orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/TheragnosticGallium67.png'),
                // decayimage2: require('../assets/radioisotopeimages/diagnoticimages/TheragnosticGallium68.png'),
            },
            {
                id: 'e14',
                name: 'Yttrium-86/Yttrium-90',
                symbol: 'Y-86/Y-90',
                period: 5,
                group: 3,
                atomicNumber: 39,
                atomicWeight: '85.914AMU/89.90AMU',
                halfLife: '14.74hrs/64.05hrs',
                productionMethod:
                    'Cyclotron 86Sr(p n)86Y/ Generator 90Zr(n, p)90Y',
                energy: 'β+ = 535,β- = 932.4',
                energyType: 'β+/ β-',
                oxidationstate: 3,
                parentRadionuclide: 'Zr86, Y86m /Sr90, Y90m',
                decayproduct: 'Sr86/ Zr90',
                naturalstructure:
                    'α- Close packed hexagonal,β- Body centered cubic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/TheragnosticYttrium86.jpg'),
                // decayimage2: require('../assets/radioisotopeimages/diagnoticimages/TheragnosticYttrium90.png'),
            },
            {
                id: 'e15',
                name: 'Iodine-124/Iodine-131',
                symbol: 'I-124/I-131',
                period: 5,
                group: 17,
                atomicNumber: 53,
                atomicWeight: '123.906AMU/130.9AMU',
                halfLife: '4.1760days/8days',
                productionMethod: 'Cyclotron / Reactor produced',
                energy: 'β+ = 687,β- = 191',
                energyType: 'β+/ β-',
                oxidationstate: '-1,+1,+3,+5,+7',
                parentRadionuclide: 'Te-131,Te-131m',
                decayproduct: 'Te124/Xe131',
                naturalstructure: 'Base centered orthorhombic',
                // decayimage: require('../assets/radioisotopeimages/diagnoticimages/TheragnosticIodine124.jpg'),
                // decayimage2:  require('../assets/radioisotopeimages/diagnoticimages/TheragnosticIodine131.jpg'),
            },
        ],
    },
    {
        id: '4',
        // image: images.nonclinical,
        name: 'Non Clinical Radioisotope',
        date: 'General',
        elements: [
            {
                id: 'e1',
                name: 'Radium-223',
                symbol: 'Ra-223',
                period: 7,
                group: 2,
                atomicNumber: 88,
                atomicWeight: 223.01,
                halfLife: '11.43days',
                productionMethod: 'Cyclotron production',
                energy: 'α = 5716.2 , γ = 269.46',
                energyType: 'α,γ',
                oxidationstate: +0,
                parentRadionuclide: 'Th-227,Fr-223, ac-223',
                decayproduct: 'Rn-219,Pb-209',
                naturalstructure: 'body centered cubic crystal',
                // decayimage: '',
            },
            {
                id: 'e2',
                name: 'Erbium-169',
                symbol: 'Er-169',
                period: 6,
                group: 'Lanthanide',
                atomicNumber: 68,
                atomicWeight: 168.934,
                halfLife: '9.392days',
                productionMethod: 'Neutron irradiation',
                energy: 'β- = 101 , γ = 8.41',
                energyType: 'β-, γ',
                oxidationstate: +3,
                parentRadionuclide: 'Ho-169',
                decayproduct: 'Tm-169',
                naturalstructure: 'closed packed hexagonal structure',
                // decayimage: '',
            },
            {
                id: 'e3',
                name: 'Gallium-64',
                symbol: 'Ga-64',
                period: 4,
                group: 13,
                atomicNumber: 31,
                atomicWeight: 63.93,
                halfLife: '2.627mins',
                productionMethod: 'Cyclotron production',
                energy: 'β+ = 1333.9 , γ = 991.56',
                energyType: 'β+,γ',
                oxidationstate: +3,
                parentRadionuclide: 'Ge-64',
                decayproduct: 'Zn-64',
                naturalstructure: 'Orthorhombic',
                // decayimage: '',
            },
            {
                id: 'e4',
                name: 'Holmium-166',
                symbol: 'Ho-166',
                period: 6,
                group: 'Lanthanide',
                atomicNumber: 67,
                atomicWeight: 165.93,
                halfLife: '26.824hrs',
                productionMethod: 'Neutron irradiation',
                energy: 'β- = 651.3 , γ = 80.57',
                energyType: 'β-, γ',
                oxidationstate: +3,
                parentRadionuclide: 'Dy-166',
                decayproduct: 'Er-166',
                naturalstructure: 'hexagonally close packed(HCP)',
                // decayimage: '',
            },
            {
                id: 'e5',
                name: 'Iridium-194',
                symbol: 'Ir-194',
                period: 6,
                group: 9,
                atomicNumber: 77,
                atomicWeight: 193.96,
                halfLife: '19.18hrs',
                productionMethod: 'Reactor produced',
                energy: 'β- = 837.8 , γ = 328.467',
                energyType: 'β-, γ',
                oxidationstate: '+1,+2,+3,+4,+9,-3',
                parentRadionuclide: 'Os-194,lr-194m1',
                decayproduct: 'Pt-194',
                naturalstructure: 'face centered cubic(FCC)',
                // decayimage: '',
            },
            {
                id: 'e6',
                name: 'Gold-198',
                symbol: 'Au-198',
                period: 6,
                group: '11(IB)',
                atomicNumber: 79,
                atomicWeight: 197.96,
                halfLife: '2.6941days',
                productionMethod: 'Nuclear reactor',
                energy: 'β- = 314.78 , γ = 411.8',
                energyType: 'β-, γ',
                oxidationstate: '+1,+3',
                parentRadionuclide: 'Au-198m1',
                decayproduct: 'Hg-198',
                naturalstructure: 'face centered cubic(FCC)',
                // decayimage: '',
            },
            {
                id: 'e7',
                name: 'Actinium-255',
                symbol: 'Ac-225',
                period: 7,
                group: 'Actinides',
                atomicNumber: 89,
                atomicWeight: 225.02,
                halfLife: '9.920days',
                productionMethod: 'Nuclear reaction',
                energy: 'α = 5830 , γ = 99.8',
                energyType: 'α ,γ',
                oxidationstate: +3,
                parentRadionuclide: 'Ra-225,Th-225,Pa-229',
                decayproduct: 'Fr-221',
                naturalstructure: 'face centered cubic(FCC)',
                // decayimage: '',
            },
            {
                id: 'e8',
                name: 'Fermium-255',
                symbol: 'Fm-255',
                period: 7,
                group: 'Actinides',
                atomicNumber: 100,
                atomicWeight: 225,
                halfLife: '20.07hrs',
                productionMethod: 'Neutron irradiation',
                energy: 'α = 7022.3 , γ = 81.48',
                energyType: 'α,γ',
                oxidationstate: +3,
                parentRadionuclide: 'Md-255,Es-255,No-259',
                decayproduct: 'Cf-251',
                naturalstructure: 'face centered cubic(FCC)',
                // decayimage: '',
            },
            {
                id: 'e9',
                name: 'Cesium-137',
                symbol: 'Cs-137',
                period: 6,
                group: 1,
                atomicNumber: 55,
                atomicWeight: 136.9,
                halfLife: '30.08years',
                productionMethod: 'Nuclear fission',
                energy: 'β- = 174.32 , γ = 661.657',
                energyType: 'β-,γ',
                oxidationstate: +1,
                parentRadionuclide: 'Xe-137',
                decayproduct: 'Ba-137',
                naturalstructure: 'body centered cubic crystal',
                // decayimage: '',
            },
            {
                id: 'e10',
                name: 'dysporium-165',
                symbol: 'Dy-165',
                period: 6,
                group: 'Lanthanide',
                atomicNumber: 66,
                atomicWeight: 164.931,
                halfLife: '2.332hrs',
                productionMethod: 'Neutron irradiation',
                energy: 'β- = 453.7 , γ = 94.7',
                energyType: 'β-,γ',
                oxidationstate: +3,
                parentRadionuclide: 'Tb-165,Dy-165m1',
                decayproduct: 'Ho-165',
                naturalstructure: 'hexagonally close packed(HCP)',
                // decayimage: '',
            },
            {
                id: 'e11',
                name: 'Selenium-75',
                symbol: 'Se-75',
                period: 4,
                group: 16,
                atomicNumber: 34,
                atomicWeight: 74.922,
                halfLife: '119.78days',
                productionMethod: 'Neutron reactor',
                energy: 'γ = 264.65',
                energyType: 'γ',
                oxidationstate: '-2, +4 and +6',
                parentRadionuclide: 'Br-75',
                decayproduct: 'As-75',
                naturalstructure: 'trigonal',
                // decayimage: '',
            },
            {
                id: 'e12',
                name: 'Potassium-42',
                symbol: 'K-42',
                period: 4,
                group: 1,
                atomicNumber: 19,
                atomicWeight: 41.962,
                halfLife: '12.355hrs',
                productionMethod: '',
                energy: 'β- = 1565.86 , γ = 1524.6',
                energyType: 'β-,γ',
                oxidationstate: +1,
                parentRadionuclide: 'Ar-42',
                decayproduct: 'Ca-42',
                naturalstructure: 'body centered cubic(BCC)',
                // decayimage: '',
            },
            {
                id: 'e13',
                name: 'Americium-241',
                symbol: 'Am-241',
                period: 7,
                group: 'Actinides',
                atomicNumber: 95,
                atomicWeight: 241.056,
                halfLife: '432.6years',
                productionMethod: 'Nuclear reactor',
                energy: 'α = 5485.56 , γ = 59.54',
                energyType: 'α,γ',
                oxidationstate: '+2,+3,+4,+5,+6',
                parentRadionuclide: 'Pu-241,Cm-241,Bk-245',
                decayproduct: 'Np-237',
                naturalstructure: 'double hexagonal close packed(DHCP)',
                // decayimage: '',
            },
        ],
    },
]
